name: foo-pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --include dev

      - name: Build
        run: npm run build --workspace packages/foo

      - name: Test
        run: npm run test --workspace packages/foo

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: foo-pr
          path: |
            ./**/lib/
            ./**/spec/
            ./**/tsconfig.tsbuildinfo

      - name: Publish unit test results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: Unit tests (foo-pr)
          comment: true
          detailed_summary: true
          group_suite: true
          report_paths: '**/spec/junit.xml'
          require_tests: true

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write
